<?php
/**
 * @file
 * Add fields to orders and products to describe Aegir products
 * 
 * TODO add fields to orders to contain serialized data describing aegir products and relationships to aegir sites and clients
 * TODO add fields to products to contain information about aegir features that trigger remote operations
 * TODO add fields to users to contain relationship info to clients and users in the aegir instance
 */
